"""Reusable, fail-closed Neon/RVV elementwise compiler."""

from .capabilities import (
    IntrinsicCapability,
    IntrinsicRole,
    LayoutKind,
    LayoutViewCapability,
    ScheduleFamilyCapability,
    ScheduleKind,
)
from .contracts import (
    ContractParseError,
    ParsedAssertion,
    parse_assertion,
    translate_assertions,
)
from .intrinsics import (
    IntrinsicResolutionError,
    ResolvedIntrinsicSet,
    resolve_intrinsics,
)
from .recognize import PairRecognition, RecognitionError, recognize_pair
from .schema import (
    BOOL,
    SIZE_T,
    Architecture,
    ArtifactKind,
    CapabilityRef,
    ClaimScope,
    ContractBinding,
    ContractExpr,
    ContractOp,
    ContractType,
    ContractTypeKind,
    ElementwiseSchemaError,
    EntryContract,
    GeneratedArtifact,
    LayoutInstance,
    LocalAssertionFact,
    ProgramManifest,
    ProofTask,
    Result,
    ResultStatus,
    ScheduleInstance,
    SourceArtifact,
    canonical_json,
    canonical_sha256,
)

__all__ = [
    "BOOL",
    "SIZE_T",
    "Architecture",
    "ArtifactKind",
    "CapabilityRef",
    "ClaimScope",
    "ContractBinding",
    "ContractExpr",
    "ContractOp",
    "ContractType",
    "ContractTypeKind",
    "ContractParseError",
    "ElementwiseSchemaError",
    "EntryContract",
    "GeneratedArtifact",
    "IntrinsicCapability",
    "IntrinsicResolutionError",
    "IntrinsicRole",
    "LayoutInstance",
    "LayoutKind",
    "LayoutViewCapability",
    "LocalAssertionFact",
    "ProgramManifest",
    "ParsedAssertion",
    "PairRecognition",
    "ProofTask",
    "Result",
    "ResultStatus",
    "RecognitionError",
    "ResolvedIntrinsicSet",
    "ScheduleInstance",
    "ScheduleFamilyCapability",
    "ScheduleKind",
    "SourceArtifact",
    "canonical_json",
    "canonical_sha256",
    "parse_assertion",
    "recognize_pair",
    "resolve_intrinsics",
    "translate_assertions",
]
